name: Build Resume

on:
  push:
    branches: [ main ]
    paths:
      - 'resume.typ'
      - 'build-typst.sh'
      - '.github/workflows/build-resume.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Typst
      uses: typst-community/setup-typst@v4
      with:
        typst-version: 'latest'
    
    - name: Build Resume
      run: |
        chmod +x build-typst.sh
        ./build-typst.sh
        
    - name: Upload Resume as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf
        
    - name: Commit and Push PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.pdf
        git diff --staged --quiet || git commit -m "🤖 Update resume.pdf"
        git push